version: '3.1'

services:
  server:
    container_name: pathfinder
    command: node --watch ./dist/server.js
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_pathfinder
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./mongoDB:/var/lib/mongo
