version: '3.1'

services:
  # node_server: 
  #   container_name: pathfinder
  #   command: node --watch ./dist/server.js
  #   build: .
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   environment:
  #     - PORT=${PORT}

  mongo :
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kmutt
      - MONGO_INITDB_ROOT_PASSWORD=kmutt
    volumes:
      - ./data:/data/db
    