version: '3.1'

services:
  node_server: 
    container_name: pathfinder
    command: node --watch ./dist/server.js
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=${PORT}

  mongo :
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kmutt
      - MONGO_INITDB_ROOT_PASSWORD=kmutt
    volumes:
      - ./data:/data/db
    
  # mongo-express:
  #   image: mongo-express
  #   container_name: my_mongo_express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=kmutt
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=kmutt
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_BASICAUTH_USERNAME=kmutt
  #     - ME_CONFIG_BASICAUTH_PASSWORD=kmutt
  #     - ME_CONFIG_MONGODB_URL=mongodb://admin:password@localhost:27017/
  #   depends_on:
  #     - mongo